name = "starbin"
type = "webpack"
account_id = "6e8f81ce0e8ba25c184fa66b5fea3ac1"
workers_dev = false
zone_id = "e8f61d23932aca701b7b4d904f039df5"

routes = [
  "https://starb.in/raw*",
  "https://starb.in/documents*",
]

kv_namespaces = [{ binding = "STORAGE", id = "0e1f192c2b40469bb88808cbaaa7355e" }]
